[package]
name = "cup"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
dotenv = "0.15.0"
rouille = "3.6.2"
shlex = "1.3.0"
tokio = { version = "1.39.2", features = ["full"] }
